products/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^products/', views.product, name='product'),
    url(r'^tickets/', views.tickets, name='tickets'),
]

video/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from products import urls as product_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^landing/$', TemplateView.as_view(template_name="landing.html")),
    url(r'^', include(product_urls, namespace="products")),
]

products/models.py
from django.db import models


class SupportTicket(models.Model):
    """
        Represents a single support ticket in the customer service system.
    """
    endpoint = models.CharField(max_length=512)
    product_url = models.CharField(max_length=2048)

products/views.py
import requests
from django.shortcuts import render

from .models import SupportTicket


# List endpoint for the starwars ship API
SWAPI = 'http://swapi.co/api/starships'


def index(request):
    resp = requests.get(SWAPI)
    if resp.status_code is not 200:
        return render_template('500.html')
    products = resp.json()
    return render(request, 'index.html', {'products': products['results']})


def product(request):
    swapi_ship_url = request.GET.get('url', '')
    results = requests.get(swapi_ship_url)
    return render(request, 'product.html', {'product': results.json()})


def tickets(request):
    tickets = SupportTicket.objects.all()
    return render(request, 'tickets.html', {'tickets': tickets})


def ticket(request):
    pass

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Customer Service with Twilio Video</title>
        <!-- Twilio shortcut icons-->
        <link rel="shortcut icon" href="//twilio.com/bundles/marketing/img/favicons/favicon.ico">
        <link rel="apple-touch-icon" href="//twilio.com/bundles/marketing/img/favicons/favicon_57.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/bundles/marketing/img/favicons/favicon_72.png">
        <link rel="apple-touch-icon" sizes="114x114" href="//twilio.com/bundles/marketing/img/favicons/favicon_114.png">
        <!-- Include Font Awesome Icons-->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
        <!-- Twitter Bootstrap included for some basic styling-->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <!-- HTML 5 shims for older IE-->
        <!--[if lt IE 9]>
            <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js">
            </script>
            <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js">
            </script>
        <![endif]-->
        <!-- Include jQuery and Bootstrap scripts-->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    </head>
    <body>
        <div id="main" class="container">
            {% block content %}{% endblock %}
        </div>
        <footer class="container">
            Made with <i class="fa fa-heart"></i> by your pals 
            <a href="http://www.twilio.com">@twilio</a>. Data courtesy of the
            <a href="http://swapi.co/">The Star Wars API</a>.
        </footer>
    </body>
    {% block js_body %}{% endblock %}
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Watto's Budget Starship Emporium</h1>
    <p>
        Step right up and browse the finest selection of gently 
        used starships in the Outer Rim Territories, fit for every budget!
    </p>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <tr>
                    <th>Model</th>
                    <th>Manufacturer</th>
                    <th>Crew</th>
                    <th>Passengers</th>
                    <th>Price (Credits)</th>
                </tr>
                {% for product in products %}
                <tr>
                    <td><a href="{% url "products:product" %}?url={{ product.url }}">{{ product.model }}</a></td>
                    <td>{{ product.manufacturer }}</td>
                    <td>{{ product.crew|default:0 }} </td>
                    <td>{{ product.passengers|default:0 }} </td>
                    <td>{% include "partials/_cost_in_credits.html" %}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

templates/partials/_cost_in_credits.html
{% load staticfiles %}

{% if product.cost_in_credits == 'unknown' %}
    Talk to sales
{% else %}
    {{ product.cost_in_credits }} 
    <span class="credits">
        <img src="{% static 'img/credits.svg' %}">
    </span>
{% endif %}

templates/partials/_ship_detail.html
<table class="table">
    <tr>
        <th>Starship Class</th>
        <td>{{ product.starship_class }}</td>
    </tr>
    <tr>
        <th>Manufacturer</th>
        <td>{{ product.manufacturer }}</td>
    </tr>
    <tr>
        <th>Cost (Credits)</th>
        <td>{% include "partials/_cost_in_credits.html" %}</td>
    </tr>
    <tr>
        <th>Length</th>
        <td>{{ product.length|default:0 }} meters</td>
    </tr>
    <tr>
        <th>Max Speed (Megalight)</th>
        <td>{{ product.MGLT|default:0 }} 
            <a href="http://starwars.wikia.com/wiki/Megalight" 
               target="_blank">MGLT</a></td>
    </tr>
    <tr>
        <th>Crew</th>
        <td>{{ product.crew|default:0 }} 
    </tr>
    <tr>
        <th>Passengers</th>
        <td>{{ product.passengers|default:0 }} 
    </tr>
</table>

templates/partials/_video.html
<!-- stubbed out for video -->

templates/product.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<h1>{{ product.name }}</h1>
<div class="row">
    <div class="col-md-6">
        <p><a href="/">&lt;&lt; View All Ships</a></p>
        {% include "partials/_ship_detail.html" %}
    </div>
    <div class="col-md-6 video">
        <button id="help" class="btn btn-primary">Need Help? 
            Chat with Support Now!</button>
        {% include "partials/_video.html" %}
    </div>
</div>
{% endblock %}

{% block js_body %}
    <script src="{% static 'js/product.js' %}"></script>
{% endblock %}

templates/tickets.html
{% extends "base.html" %}

{% block content %}
<h1>Current Support Tickets</h1>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>Product</th>
                <th>Time In Queue</th>
                <th>Handle Ticket</th>
            </tr>
            {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.product_url }}</td>
                <td></td>
                <td><a href="#">Help Customer</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}